#!/bin/bash

. version

tmp=./$$
base=$tmp/$vername

trap "/bin/rm -rf $tmp" 0

if [ -r ./config.status ]
then
    ./config.status
elif [ -r ./configure ]
then
    ./configure
else
    echo "Cannot configure to get a .spec file" 1>&2
    exit 1
fi

make README.html

mkdir -p $base

cp -r \
    LICENSE \
    README.md \
    README.html \
    *.in \
    Makefile \
    Magdir \
    compile.py \
    configure \
    epilogue.c \
    generate.py \
    libmimemagic.spec \
    magic \
    mime.exceptions \
    mimemagic.c \
    mimemagic.h \
    mimemagic.man \
    original_list \
    prologue.c \
    utils.py \
    $base

(cd $tmp && tar zcf ../${tar} $vername)
